### ISSUE TITLE
Show status question

### ISSUE THREAD

**Issue by Xmetalfanx** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#104]
We should get input from @ChrisLAS / Noah on the status of Ask Noah and Tech Talk Today... I see both shows on the "archived" part of the JB site.  I know it seemed like TTT may be coming back a few months ago and wouldn't want to move it back to the archived section for no reason .. but if both shows are archived now, we should move them out of the "active show" section

**Comment by Xmetalfanx** [comment]
This one i know ended but forgot to mention it ... Unfilter too

**Comment by Xmetalfanx** [comment]
I just submitted a PR to address Choose Linux, and archived TTT, as well as Unfilter. 

The funny one is Ask Noah.   I admit I am behind and may tweet, Chris and Noah about this but

- The JB site ends at Ask Noah 100, even though the show is going on https://podcast.asknoahshow.com/ with new episodes ... 
- testing my PR before i submitted anything the JB Kodi addon DOES show and play the new Ask Noah episodes from what I can see.   
- Ask Noah is still listed in Discord for JB, although I dont see the JB account tweeting anything (like "Ask Noah is on now") since last November.

Really it doesn't matter to me, I was just going to move the show to the archive section to reflect JB's site ( https://www.jupiterbroadcasting.com/show/asknoah/ )  but I am not sure what to do with that (It's Chris's/Noah's choice really) .. I may have missed some announcement a few months back 

PR: https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting/pull/107

**Comment by rickyphewitt** [comment]
Its probably worth confirming with a tweet on Ask Noah.  The PR looks good and I can merge it unless there is any reason not to.

**Comment by RobLoach** [comment]
Makes sense to represent what's presented on the website, but you're right that it doesn't hurt to ask. Just tweeted!
https://twitter.com/RobLoach/status/1114878191439683584

**Comment by Xmetalfanx** [comment]
I just read Noah's response and I will leave it up to you guys (heck i just help out when i can, you guys do the heavy lifting w/ the code) .... I can see it both ways ... 

- move it to archived to reflect the JB site since it's an active show, but not associated with Jupiter Broadcasting now, even if it's still active

- keep it where it is now until maybe a different "Ask Noah" Addon is coded... this addon would have full control basically of what Noah/Altispeed wants it to be.

**Comment by Xmetalfanx** [comment]
after reading a number of responses I think it may be worth moving it now to archived shows to stay consistent with JB

**Comment by Xmetalfanx** [comment]
https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting/commit/04797ab9bee3b60bac478dfc4b8239a036c45e20 addresses Tech Talk Today and Unfilter

**Comment by Xmetalfanx** [comment]
https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting/commit/60aaecb09e730443a48617fd5c4b9848acda0a83 seems to address Ask Noah and I am staying out of it .... 

my point on Twitter was seeing if it'd be an answer like A) "Let's keep it consistent with the JB site guys" (makes sense) ... or B) Yeah, AskNoah doesn't have anything to do with JB anymore other than the first 100 episodes or so was on JB... but for listening to past episodes, considering there is currently no stable version of an Ask Noah Addon .... to help Noah out in a sense, you can just leave it with the active shows, and once there is a stable addon, then you guys can change it"

**Comment by RobLoach** [comment]
Yeah, let's archive it after the next release.

**Comment by RobLoach** [comment]
Definitely want to give the show as much presence and attention as possible! Thanks so much for putting together the new addon 😃
