### ISSUE TITLE
Not working on  OpenELEC Raspberry Pi ARM Version:3.0.6

### ISSUE THREAD

**Issue by ghost** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#12]
Hi the addon works just fine on my ATOM system.
For the second tv i have a Raspberry Pi and the addon does not work.

Loading the feeds takes very long and after some time it crashes.

**Comment by RobLoach** [comment]
Do you know which version of XBMC Raspberry Pi/OpenELEC uses? I've sent a recent update request to them that might fix a few things.
http://sourceforge.net/mailarchive/forum.php?thread_name=CAAqBA1yKxMc36EXF3CcD%3D%2BSdduVNO%2BebX2JapQ%2BUL0P7QbZz2w%40mail.gmail.com&forum_name=xbmc-addons

Thanks!

**Comment by RobLoach** [comment]
Updates are out.

**Comment by RobLoach** [comment]
Let me know how the update goes for you.
