### ISSUE TITLE
The Linux Action Show and Jupiter Broadcasting Logos, need to be updated.

### ISSUE THREAD

**Issue by madpipeline** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#17]
Jupiter broadcasting and The Linux Action Show have new logos. They need to be updated.

**Comment by keobrien08** [comment]
New pull request adds new logos for LAS and Linux Unplugged. 

-Rob: I did notice when I changed the Jupiter Broadcasting Images on my rpi xmbc it still showed the old images even though they were not present on harddrive. I did get the logo and fan art to work correctly by uninstalling and installing via the .zip method and changing file name to plugin.vide.jupiterbroadcasting2.zip and then everything worked smoothly. Not sure if this is a bug with where XMBC pulls information for plugins in their repos so it may correct itself when you send a request to update to them.

**Comment by RobLoach** [comment]
Merged :+1:
