### ISSUE TITLE
Slow to load

### ISSUE THREAD

**Issue by madpipeline** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#18]
On OpenElec (running on Raspberry Pi) the loading of the list of shows, and/or list of episodes is extremely slow (more that 10 minutes).

**Comment by RobLoach** [comment]
Wow, is it because the Raspberry Pi is slow? Or the parsing of the XML? Any ideas? I'm assuming your network is fine.

**Comment by keobrien08** [comment]
I run it on my Raspberry Pi, running Raspbmc and there isn't that much of the delay. What version of OpenElec are you running? I know newer ones based on the latest Raspbian image allows for the over clocking of the cpu which may help.

**Comment by madpipeline** [comment]
I'll reinstall OpenElec, to have the latest, I'll come back with feedback.

**Comment by rickyphewitt** [comment]
@ovidiub13 are you still experiencing this issue? I have not seen this delay on my RP2.

**Comment by rickyphewitt** [comment]
@RobLoach I vote we close this issue if there is no response

**Comment by madpipeline** [comment]
I don't use this plugin anymore, so I cannot provide any more feedback on it. Closing it is a good action. Thank you.

**Comment by RobLoach** [comment]
Thanks for the feedback, @ovidiub13! If you try it out again, let us know if you see any slowdown.

**Comment by Xmetalfanx** [comment]
Yeah I am also thinking the fact that it was on a pi .. that may factor into it .. as someone who DOESN'T have a Pi 3 yet ... I even just noticed an overall kodi improvement going from a Pi B+ to a Pi 2 .. .internet connection MAY also factor in.
