### ISSUE TITLE
Add Tech Talk Today

### ISSUE THREAD

**Issue by RobLoach** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#24]
http://imgur.com/KrxMqhD

**Comment by keobrien08** [comment]
Im not sure if this show is going to be handled the normal way, I will see what happens with it this week and try and submit something

**Comment by RobLoach** [comment]
Mos' Def! Thanks for staying in touch, @keobrien08 :+1:

**Comment by keobrien08** [comment]
Ok it looks like they will be also hosting the videos on jb site, after I sign up to donate, I'll contact Angela and get an official image for it, and work on the code.

**Comment by keobrien08** [comment]
Just talked with Angela, and will be getting the image for the show within the next few days, the codes all set. As soon as I get the image I'll wrap it up into one bit commit
