### ISSUE TITLE
Push to Xbmc repo

### ISSUE THREAD

**Issue by keobrien08** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#31]
Do you know when this will actually get pushed to xbmc repo? Still shows 3.0.4 in official repo

**Comment by RobLoach** [comment]
Whenever we want it to go up. Things we'd need to do:
- [x] Decide if there's anything else we want in `3.1.0`
- [x]  Tag 3.1.0
- [x] [Send them an email](http://wiki.xbmc.org/index.php?title=Submitting_Add-ons#How_to_submit_your_add-on_and_subsequent_updates)

So, is there anything else we should update?

**Comment by keobrien08** [comment]
I think its good to go, i've been running it in beta so far on my pi just by compiling it into a zip. I agree with the overhaul of the images, but we will need to get Angela involved with that. At least if we get it in there, people can start enjoying the new content on the Xbmc and we can push out fixes as we see them

**Comment by keobrien08** [comment]
I'm definitely comfortable with the 3.1 release

**Comment by RobLoach** [comment]
- Email sent: http://sourceforge.net/p/xbmc/mailman/message/32433003/
- Will need to create a new branch for gotham: https://github.com/RobLoach/plugin.video.jupiterbroadcasting/issues/36

Thanks so much for all the testing!
