### ISSUE TITLE
Fix Show Order

### ISSUE THREAD

**Issue by RobLoach** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#32]
Should show [All Shows] and [Live] first in the list.

**Comment by keobrien08** [comment]
by all shows do you mean most recent?

**Comment by RobLoach** [comment]
On the main page, it displays:
- Live Show
- In Depth Look
- Most Recent
- TechSnap
- ...

Live Show and Most Recent should likely be the first listed.

**Comment by keobrien08** [comment]
Ok I will look into it, I warn I am very novice at python only really started reading about it, so my troubleshooting is still a little slow but I will try my best to step up my efforts to learn. Part of the reason I wanted to get involved in a project.

**Comment by keobrien08** [comment]
so looking at the code can you point me in the direction of where it actually goes about generating teh list of shows in regards to their order? is the loop on 256?

**Comment by MichaelTunnell** [comment]
I agree with this bug it should be 
- Live Show (now JBLive.TV)
- Most Recent
- Alphabetical listing of shows...currently there seems to be no order at all for how they show.
