### ISSUE TITLE
Archive Folder Needed

### ISSUE THREAD

**Issue by MichaelTunnell** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#39]
I think the archived shows should actually be put in an Archive so they don't show with all the active shows in the front page of the addon.
- JBLive.TV
- Most Recent
- Archive
- Alphabetical listing of the active shows

**Comment by RobLoach** [comment]
Definitely, no reason to show archived shows on the homepage. Would be nice to split them into sub-folder.
