### ISSUE TITLE
Failed, Check the log file.

### ISSUE THREAD

**Issue by nzcarrick** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#41]
When clicking on an item, I regularly get the following error. when i copy and paste into chrome the URL, it redirects and plays fine. i am running the latest stable openelec. addin version is 3.1.1
Here is the error:

21:07:18 T:140522790733632  NOTICE: DVDPlayer: finished waiting
21:07:18 T:140521585334016  NOTICE: Thread JobWorker start, auto delete: true
21:07:20 T:140521012004608  NOTICE: Thread BackgroundLoader start, auto delete: false
21:07:23 T:140522790733632  NOTICE: DVDPlayer: Opening: http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/techsnap/2014/techsnap-0184.mp4
21:07:23 T:140522790733632 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:07:23 T:140521012004608  NOTICE: Thread DVDPlayer start, auto delete: false
21:07:23 T:140521012004608  NOTICE: Creating InputStream
21:07:23 T:140521012004608  NOTICE: Creating Demuxer
21:07:23 T:140520189851392  NOTICE: Thread FileCache start, auto delete: false
21:07:37 T:140522790733632  NOTICE: NFS is idle. Closing the remaining connections.
21:07:53 T:140521012004608   ERROR: Open - Error, could not open file http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/techsnap/2014/techsnap-0184.mp4
21:07:53 T:140521012004608   ERROR: OpenDemuxStream - Error creating demuxer
21:07:53 T:140521012004608  NOTICE: CDVDPlayer::OnExit()
21:07:53 T:140521012004608  NOTICE: CDVDPlayer::OnExit() deleting input stream
21:07:53 T:140522790733632   ERROR: Playlist Player: skipping unplayable item: 0, path [http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/techsnap/2014/techsnap-0184.mp4]
21:07:53 T:140522790733632  NOTICE: CDVDPlayer::CloseFile()
21:07:53 T:140522790733632  NOTICE: DVDPlayer: waiting for threads to exit
21:07:53 T:140522790733632  NOTICE: DVDPlayer: finished waiting
21:07:53 T:140522790733632  NOTICE: CDVDPlayer::CloseFile()
21:07:53 T:140522790733632  NOTICE: DVDPlayer: waiting for threads to exit
21:07:53 T:140522790733632  NOTICE: DVDPlayer: finished waiting

**Comment by RobLoach** [comment]
Can you verify your Internet is up? Looks like URLs are working.

**Comment by nzcarrick** [comment]
I think it might be something to do with squid caching in pfsense. The internet was definitely up at the time

On 8 February 2015 11:58:33 GMT+13:00, Rob Loach notifications@github.com wrote:

> Can you verify your Internet is up? Looks like URLs are working.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/RobLoach/plugin.video.jupiterbroadcasting/issues/41#issuecomment-73387540

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rickyphewitt** [comment]
@nzcarrick Is this still an issue? I run OpenElec on my pi and have not experienced this. Is it a specific show? I've only really tried linux/unplugged/coder/unfilter via kodi

**Comment by rickyphewitt** [comment]
@RobLoach I vote we close this issue if there is no response
