### ISSUE TITLE
Add option to choose Live Stream feed (RTSP/RTMP/HLS/Audio)

### ISSUE THREAD

**Issue by kaipee** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#44]
Sometime over the past few weeks, prior to Christmas, the stream got really 'choppy' when played on my CuBox-i4 Pro. Even on my main rig it occasionally seems to buffer.

On the CuBox the stream opens and plays for about 3 seconds, then video stutters while audio plays for about another 2 seconds, then both audio and video constantly stutter.

System resources all seem fine on the device and all other streams playback fine (including 1080p content).

**Comment by allanjude** [comment]
There was an issue with the stream for about a week. Does it play properly now?

**Comment by MichaelTunnell** [comment]
Yea, I dont think this is a addon specific issue but rather the stream issue that was happening. The addon on the pi works fine when the stream is solid.

**Comment by kaipee** [comment]
I'll test the cubox-i tomorrow again. Are there any specific logs or outputs from terminal tools you would like?

I did notice that, this week, the RTMP stream regularly froze / died through VLC.
Here is an output from a crashed VLC playback on my main rig: http://pastebin.com/Sfc84egy

**Comment by kaipee** [comment]
Just a note for myself to test (and for future readers) : http://www.solid-run.com/community/topic1876.html

**Comment by kaipee** [comment]
Ok, so here is a video a took with my Nexus 6 which outlines the stuttering. Please enable annotations as I have added notes.

You can clearly see that the Live Stream has issues with playback after a few seconds - whereas HD playback plays, skips and fast-forwards without issues both from JB library and YouTube (1080p).

https://www.youtube.com/watch?v=1PEHUzim0dw
(please forgive the messy navigation, I haven't finished setting up lirc on my remote yet)

**Comment by kaipee** [comment]
I have just applied the advancedsettings.xml as per my previous comment.

The stream seems to be working perfectly today. Not sure if some changes were made to the stream or if the advancedsettings.xml had fixed it.

Could someone please clarify before closing?

**Comment by kaipee** [comment]
Nope, seems to be broken again. Same stuttering and freezing.
Was something changed during the past week-ish?

**Comment by kaipee** [comment]
OK, so it seems to be working again.

I'm starting to think that only the pre-recorded 'live stream' playback works fine - but the actual LIVE livestream is what is having problems. I'll test later today with LAS Live (I was watching pre-recorded livestream all day without issue)

**Comment by kaipee** [comment]
Yeah it's definitely the Live livestream.

Chris just put up the Live show for testing Xonotic and my XBMC immediately started to stutter again. Not only that but my main Arch rig is forever buffering every few minutes.

Edit: .....and now the add-on just crashed on my main rig

**Comment by kaipee** [comment]
The problem is with the RTMP stream (which I'm assuming the add-on uses).

I manually created 2 .STRM files - one with the RTSP stream, the other with the RTMP stream.
The RTMP file causes the same stuttering problems.
The RTSP plays fine and is still currently streaming without issue.

@allanjude anything noticed on your end for the RTMP stream?

**Comment by RobLoach** [comment]
Switching scope to allow choosing which stream to use. Audio might be an option if video is laggy.

**Comment by RobLoach** [comment]
This is in place. @rikai just updated it to default to RTMP.
