### ISSUE TITLE
Add Screenshot

### ISSUE THREAD

**Issue by RobLoach** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#49]

**Comment by MichaelTunnell** [comment]
lol is this related to the reddit thread about github repos not having screenshots? :)

**Comment by RobLoach** [comment]
Haha, probably... And it's true! http://betterexplained.com/articles/adept-method/

**Comment by MichaelTunnell** [comment]
Well I'll add it to my to-do list. ;)

**Comment by RobLoach** [comment]
Had added some screenshots on http://kodi.wiki/view/Add-on:Jupiter_Broadcasting . Could just use that one :wink: .
