### ISSUE TITLE
Slow on Kodi 17

### ISSUE THREAD

**Issue by RobLoach** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#52]
Seems to stall the system on Kodi 17.

**Comment by RobLoach** [comment]
@kurgan2001 tested and reported it works!

**Comment by Xmetalfanx** [comment]
I have this on my Pi2 and LibreElec 7 (based on Kodi 16) and the past 3 days or so  I can not connect to the live stream with it ... the streams via the JB website play fine when the addon is not connecting

Playing a few random videos from various shows (via the "back catalog") play no problem
