### ISSUE TITLE
Problems playing live streams

### ISSUE THREAD

**Issue by Xmetalfanx** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#54]
I have this on my Pi2 and LibreElec 7 (based on Kodi 16) and the past 3 days or so I can not connect to the live stream with it ... the streams via the JB website play fine when the addon is not connecting

Playing a few random videos from various shows (via the "back catalog") play no problem

Version 3.21 

Tried High and low quality and it seems "audio" works under "Live  stream type" but not one of the other three options is connecting for me

**Comment by RobLoach** [comment]
Interesting, seems to be working here in Kodi 17. Does it work in the browser for you?

**Comment by Xmetalfanx** [comment]
The stream? ... yes  it does ... I just noticed now that it seems that HLS is working (on the pi2 with LibreElec based on Kodi 16.x, with the JB addon ... just to be clear) ... I was asked by Allan Jude, in IRC,  to test the RTMP stream URL  with VLC on my laptop and it plays perfectly fine there. 

At least the past few times this week I tried the stream (which prompted my OP) I was mainly trying RTSP or RTMP , though a day or so ago, I couldn't even get HLS  to connect.    I figured even if it wasn't anything locally causing a problem here (at my  house that is) it could be my Comcast on my end having an issue... though after a few days of the same issue on the pi2 with the live stream and the stream perfectly fine on the computer, I figured something was "off" somewhere.

I am more than willing to admit if it turns  out to be something on my end,  though I have tried a few setting changes before even considering posting here.

**Comment by Xmetalfanx** [comment]
Just tried it again after the last post, and all streams are back to normal now ... not sure where the issue was (my router? ... my pi2? my ISP?) but I suppose this can be marked as **fixed/non-issue** now.   Still on the same LibreElec though there IS a version (alpha) based on Kodi 17.x ... all JB Kodi addon settings at the defaults.

Sorry to bother anyone with this thread.

**Comment by RobLoach** [comment]
No worries! We did change the default stream for this recently, and Kodi still hasn't updated it in the addon repo, so I hope that update helps when it comes.

Thanks a lot!
