### ISSUE TITLE
Add User Error

### ISSUE THREAD

**Issue by RobLoach** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#55]
http://www.jupiterbroadcasting.com/show/error/

@rikai Do you know the RSS feeds for this one?

**Comment by MichaelTunnell** [comment]
There is currently only an MP3 feed for User Error. I am not sure if there is any plan for a video feed or not but I suspect there isn't because the show is 100% audio based podcast.

https://feedpress.me/usererror

**Comment by RobLoach** [comment]
Began adding this over at https://github.com/RobLoach/plugin.video.jupiterbroadcasting/pull/56 , ran into a few issues. May need some tweaks.

**Comment by ChrisLAS** [comment]
User Error has a newish Video feed here: https://feedpress.me/uevideo

**Comment by Xmetalfanx** [comment]
I am new to git ... somewhat ..... but i made a few changes 

https://github.com/Xmetalfanx/plugin.video.jupiterbroadcasting and it seems to work ... it has the feeds in my tests with Kodi,  and it displays the user error graphic i downloaded from the JB site ... I  just haven't gotten it to show "user error" on the Kodi menus"

**Comment by Xmetalfanx** [comment]
still  tweaking a thing or two (like the size and spacing of the image to match the other graphics sizes better) but functionally, in my tests, here it seems to work .. there is now a User Error entry in the menu, and the show list comes up when you click on it ... 

The thing I am not sure if i had in earlier versions of my fork, and then I broke something (not sure if i did) is that the graphic for user error is not showing when you highlight different episodes... I want to get that figured out

**Comment by Xmetalfanx** [comment]
OK sorry it's taking so long guys ... I am learning as I go ... I finally got my brain wrapped around squashing commits (thanks to Rikai's help)   and combined them though I think something may have gone wrong when I tried to (?? my terminology) sync my branch and what I have at the moment with the changes made in the past day or so with the original repo.  

I think its complaining about some conflicts right now and I just hope with all that I did today I didn't actually break the functionality of what I added yesterday, lol.

For JB's sake I will try to get this all buttoned up ASAP.

**Comment by RobLoach** [comment]
Merged manually! Well done :+1: .

Was there anything else we needed to stick in here to get User Error up and running?

**Comment by Xmetalfanx** [comment]
Not that I know of ... I know Rikai said somewhere (losing track of where messages are now) something about the encoding so some shows MAY not play on certain devices ... though that is out of my hands.   Apparently they are trying/doing something different with User Error ... I rather not speak FOR Rikai though

**Comment by rickyphewitt** [comment]
User Error is available in the plugin
