### ISSUE TITLE
Unit Tests for Addon

### ISSUE THREAD

**Issue by rickyphewitt** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#61]
I know the addon is a small code base, but I think adding a subfolder with tests, maybe a make target to run them would help. I did some minor research and found a post about it:
- http://jonathanbeluch.com/blog/2012/09/testing-xbmc-addons/

Might be a good place to start.

Thoughts?

**Comment by rickyphewitt** [comment]
The plugin directly imports various XBMC specific modules and they don't seem to be pip installable. This may make unit testing difficult.

**Comment by RobLoach** [comment]
Would be great to be able to unit test the addon!

**Comment by rickyphewitt** [comment]
I think if I can break out the non Kodi specific code we can get some unit tests.

**Comment by rickyphewitt** [comment]
I've taken a small stab at adding unit tests, makefile, and vitualenv. Readme gives an overview on how to setup and run the tests. I use arch so I have 2 make targets, I haven't been able to test the non arch ones, going to target ubuntu for those targets. 

Right now there is a single test that validates shows have the required attributes.

Biggest downside to adding unit tests is the repo structure is going to change.. a lot. My initial view: default.py just contains api/glue calls to xbmc where all other non xbmc code is contained in separate files. 

Initially I attempted to mock out a kodi addon module, but I'm not that familiar with the addon api. The docs from kodi don't show the modules indepth (at least for me).

Any feedback is appreciated. This change might be considered too tumultuous for the plugin

Working branch: https://github.com/rickyphewitt/plugin.video.jupiterbroadcasting/tree/unitTestSupport

**Comment by rickyphewitt** [comment]
I've cleaned up the code a bit, still need to squash merge the remote into a single commit. Tests are added for show validation. I'll run the new code through pylint and update as needed. Thinking we can incrementally chip away at unit testing the whole codebase instead of a single gigantic commit that does it all.

**Comment by rickyphewitt** [comment]
Closing as Unit tests and Travis CI have been integrated into codebase. 

When new code is committed unit tests should be required.
