### ISSUE TITLE
User Error Show descriptions showing <p> tag

### ISSUE THREAD

**Issue by rickyphewitt** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#69]
Not sure if this affects other shows, but looking at the descriptions of the User Error shows in Kodi they contain `<p>` tags. Those tags and any other html tags should be stripped out prior to setting the description. Other shows descriptions should be audited for this as well.
![20161203_104300](https://cloud.githubusercontent.com/assets/5995409/20861138/af5cc04c-b945-11e6-84d0-ce50cc079725.jpg)

**Comment by RobLoach** [comment]
Good catch... We could pass the descriptions through this regex:
http://stackoverflow.com/a/4869782

``` python
re.sub('<[^<]+?>', '', text)
```

**Comment by rikai** [comment]
I think using something from [this post](http://stackoverflow.com/questions/753052/strip-html-from-strings-in-python) may be better.

Using a regex, especially such a simple one, will run into edge cases sooner or later I'm sure so we might as well get it right the first time around, even if it does mean a bit more reading. ;)

**Comment by rickyphewitt** [comment]
Agreed @rikai.

**Comment by Xmetalfanx** [comment]
Have to say that reminds me of the Ikey view ... instead of slapping something together and having to fix more and more stuff down the road.... get it right (even if that means more work) the first time to save headaches, down the road
