### ISSUE TITLE
Move to JupiterBroadcasting GitHub Org

### ISSUE THREAD

**Issue by RobLoach** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#74]
I'm happy to keep maintaining the Kodi addon, but it may be fitting to move it over to https://github.com/JupiterBroadcasting . Thoughts?

Things we need to do:

- [x] Delete [the fork](https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting)
- [x] Add @RobLoach as an admin (to make sure tests still work)
- [x] Change ownership of the repo over to Jupiter Broadcasting
- [x] Update the `provider-name` in addon.xml
- [x] Make a new release
- [ ] Add more docs to help others maintain it?

**Comment by rikai** [comment]
Would be happy to do this when I've got some free time. The initial setup of the organization was done rather messily so I would be happy to start getting that in order. :)

**Comment by rickyphewitt** [comment]
Makes sense!

**Comment by rikai** [comment]
@RobLoach I need you to initiate [a transfer](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) and then i'll give you proper write access to the repo once it is. 👍

**Comment by RobLoach** [comment]
@rikai Done! https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting

**Comment by rikai** [comment]
@RobLoach You should now be an admin of the repo, as well as being a maintainer for the team tied to this repo, which all collaborators you listed have been sent an invite for 👍
