### ISSUE TITLE
Started adding info for Linux Action News 

### ISSUE THREAD

**Issue by Xmetalfanx** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#75]
figured someone else would beat me to this anyway, (eh well :P ) but I started adding the info for Linux Action News, though its a few weeks away from a launch and OBVIOUSLY the two biggest issues I have so far is I have no idea was the feed links will be, nor (that I can tell) do I have the graphic for the new show.    

I remember for User Error, I found an image somewhere and tried to edit it down to look best in the addon .. then Rikai  (if I recall) just linked me to the perfect sized and quality image for User Error to include anyway .

A) I am not sure if that is the right URL to use or there will be a link to the JB site that will end up being more appropriate 

B) Just thought of this ... but would LAS be considered "Archived" at that point? (at the start of LAN) ... IF SO ... I didn't make that change .. figured LAS maybe should be moved to the Archive section even at that point .. just yet ... but that would be maybe more Rikai and obviously's Chris's option on that that matters ... I don't care either way

**Comment by Xmetalfanx** [comment]
Added the new graphic for the show.

Something else came to mind ... something Chris (IIRC) said this may not be a live show... not sure if was just venting/frustrated at the time but anyway ... at any-rate ... I am not sure what to put in the most important part of this addition ... the actual "feed URLs"  ... If i haven't goofed and missed something that's all that is needed.   I would like to test this after an episode or two just to make sure its working correctly before I would submit a PR 

and I am also keeping an eye on what you guys are saying with moving the JB plugin to the JB github page instead of using this one.

**Comment by rickyphewitt** [comment]
@Xmetalfanx 
Looks good!
To address your initial question (B). I agree we should leave LAS unArchived until informed otherwise. 

I'm assuming the feed urls will be available when the show goes live.

**Comment by Xmetalfanx** [comment]
https://github.com/Xmetalfanx/plugin.video.jupiterbroadcasting/commit/0b979a44c2b543b0d77cc15e0ddfa8d889c7092a  Added the RSS stream to "audio" in the feed though when testing things on my own systems (One Ubuntu Mate 17.04 laptop and LibreElec (? 8 .... with "Kodi 17.1") on a Pi 3 .... When I open the addon, with the changes I made it says "error ... see logs" but at least the log viewer in the Kodi GUI is not showing any info .... I will try to see what is going wrong ... 

I wanted to test things with the RSS feed, but I do realize maybe when there's a show or two up (and not just that test-run episode) it may be better to see if the changes are pulling in the info correctly for each episode.

Now that LAS is over, Chris can focus more on where he wants what feeds and not "worried" (so to speak) about the final view LASs

**Comment by Xmetalfanx** [comment]
My opinion doesn't matter ... its up to the guys at JB to decided this but even not counting THAT... if there was one show not to be stuck in the archived show section of the addon ... I think it should be LAS ... its been JB's "flagship" show for so long, people may be able to find it and watch the episodes faster if it was still on the main screen.

I heard something on the live stream of the LAST LAS that I do not want to start rumors with ... but there (if the guys feel like it/want to do it) may be special episodes of LAS coming back for a one time only thing ... say once a year or something .... It WAS a "passing comment" when people were chatting though I do not think they were "100% AGAINST" that idea ... again not saying IT WOULD happen, but they have an open mind about it ....

I do KNOW LAS just ended though lol

**Comment by Xmetalfanx** [comment]
spotted y really stupid mistake (missing  closing brackets ) ... will test some things and see if it work ... with the show starting now if i am going to be doing this, I want to get it working and submit a PR ASAP for JB's sake

**Comment by Xmetalfanx** [comment]
(Removed some of my comments to clear "Chit-chat" on here)

**Comment by Xmetalfanx** [comment]
https://github.com/Xmetalfanx/plugin.video.jupiterbroadcasting/commit/c322ea81b2d7e16a2ad17147f28bf3369834786d

What I have so far ... I did have a mishap when trying to squash commits and I went one too far so I managed to just start over (hence links I removed in prior comments on this thread)   What I have above ... with a possible spelling correction should be exactly where I was before.

Thanks for the correction Rikai .. I did see that message, and I went over the few things I added to the addon and do not think I messed the name up this time 

The First episode and the pilot play on my Solus + Kodi install ... though the way it is now the episode info is not being "scraped", so that has to be fixed.  

I am not sure if there will be a feedpress "URL" for the show ... if there is changing the feed URLs to that may solve this "show info not being scraped" issue.  I cant test this on every possible device that'd have Kodi but that issue seems like one of the last ones I can see before doing a possible PR

---------------------
I seem to be having some issues possibly not related to this at all on my LibreElec install so that's why I probably am more behind on this than I want to be

**Comment by RobLoach** [comment]
Looks good! Should I cherry-pick that commit in, or will you be sending up a Pull Request? ;-)

**Comment by Xmetalfanx** [comment]
I will send a PR after this message is sent ... I figure for say the data about the episode not being pulled in (from what I can tell) ... perhaps one of you can spot whats wrong and fix it (for JB/JB's fan's sake) faster than I can spot what I am doing wrong.

Just didn't want to do a PR on something 1/2 done, at first 

give me a few minutes to clean up one commit ... I changed the audio feed URL but it still works ... just want to have a single commit when i submit the PR

**Comment by Xmetalfanx** [comment]
Not saying its done but I am closing this so there are not "useless" open issues listed.   

Also still not sure on the status of this addon moving to the JB repo which I believe is listed as another "issue"

**Comment by rikai** [comment]
I'll try to get to that this weekend.

@RobLoach Are there any official collaborators on this project other than you?

**Comment by RobLoach** [comment]
@rikai You'll find the list over at:
https://github.com/RobLoach/plugin.video.jupiterbroadcasting/graphs/contributors

A big chunk of the code is from rickyphewitt. He pretty much refactored the whole thing. MichaelTunnell, keobrien08, Xmetalfanx, everyone has had a part in maintaining it :+1:

**Comment by rikai** [comment]
Sorry, by collaborators I meant people that you wanted to have direct commit access to the repo.

**Comment by RobLoach** [comment]
Ah, thanks...

- keobrien08
- MichaelTunnell
- allanjude
- rikai
- rickyphewitt
