### ISSUE TITLE
Audio-only mode

### ISSUE THREAD

**Issue by sergioad** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#81]
Hi friend could you add an audio only mode inside the music addons like the TWiT addon? Also, LAS ended months ago, it is now Linux action news so you would need to update the addon's description

**Comment by RobLoach** [comment]
It's in the Audio Settings. Quality.
![screenshot at 2017-08-11 15-54-35](https://user-images.githubusercontent.com/25086/29229643-7a7a9966-7ead-11e7-900a-a3d4982d4a1c.png)

**Comment by RobLoach** [comment]
Creating a whole new Addon  just for Audio mode is a bit more work/maintenance than we should do. Just use Quality in the settings.

**Comment by sergioad** [comment]
It is not necesary, you can see the TWiT addon wich with only one install you get audio and video modes separated on music and video

**Comment by rickyphewitt** [comment]
@sergioad,

I believe you are referencing this twit kodi addon? https://github.com/divingmule/plugin.video.twit

If so it looks like they have specific audio and video feeds. I know JB has video/audio feeds as I mostly listen to audio via a podcast client. Just need those urls.

@rikai,

Can you provide (or point me in the right direction) for the audio only urls for JB shows?

**Comment by rikai** [comment]
Feeds should be available from the feeds dropdown on the main page on the right, or alternatively listed under any episode for a show.

**Comment by rikai** [comment]
Every show should have an audio only URL listed as the "mp3 feed"

**Comment by rickyphewitt** [comment]
Perfect!

**Comment by rickyphewitt** [comment]
Well after re-reading the issue... there is audio mode in the plugin :)

However testing out the audio I found a bug with Ask Noah/Linux Action Show audio feeds.

Added an issue for it: #86
