### ISSUE TITLE
update the addon's description

### ISSUE THREAD

**Issue by RobLoach** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#82]
From @sergioad .... 

>  LAS ended months ago, it is now Linux action news so you would need to update the addon's description

**Comment by sergioad** [comment]
Thanks :)

**Comment by Xmetalfanx** [comment]
was going to do this (just saw the message now) but i am trying to sort of syncing issues first ... ended up trying a sync to keep my branch up-to-date but ended up added a commit message .... completely unwanted on my end and it seems silly to have "sync to xmetal's branch" and another commit on my end "sync to master branch" ... I just want to sync completely (no added commits on my end) to the master branch before I do anything else.
