### ISSUE TITLE
Upgraded to Ubuntu MATE 17.10, Jupe Plugin in Kodi not working

### ISSUE THREAD

**Issue by zaivala** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#84]
Yup, I did the hot new upgrade. I was watching Unfilter on Kodi just yesterday, got about halfway through. Did the upgrade, and went back to Kodi. Other plugins work, but not Jupiter shows.  I click on Unfilter, the system locks for a few seconds, then tries to load, then informs me that it failed to load and to see the logfile.
[Kodi-Jupiter Errors.txt](https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting/files/1403336/Kodi-Jupiter.Errors.txt)

**Comment by rickyphewitt** [comment]
What version of Mate/Ubuntu did you upgrade from? The errors in the log do not seem to be related directly to the plugin code. 
I have a fresh install of 17.10 ubuntu Mate i will test the plugin on. 
In the meantime it might be worth disabling/re-enabling and/or removing/re-installing the plugin.

**Comment by rickyphewitt** [comment]
@zaivala,

I've confirmed with Ubuntu Mate 17.10 the Jupiter broadcasting plugin works. I was able to play Ask Noah, BSD Now, and Unfilter.

let me know if the above troubleshooting steps did not solve the problem and provide an additional log.
Also What version of Kodi and what version of the JB plugin.

**Comment by zaivala** [comment]
17.04. And it has only been installed on this computer for a week or two, and I was watching Jupe on Kodi just the day before this upgrade.

**Comment by zaivala** [comment]
I just tried playing Unfilter again. The cursor locked for a few seconds, but then it went ahead and played. It did not, however, retain the information about where I left off.

 This means it's working, and I don't have to reinstall. I'd hate to go through re-adding my plugins, might forget (easily) which ones I had and would still have to reconfigure those I use.

**Comment by rickyphewitt** [comment]
@zaivala,

Glad to here the plugin is working for you again! Let us know if you run into any other issues :)
