### ISSUE TITLE
Update TechSNAP feed

### ISSUE THREAD

**Issue by blkeller** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#89]
The feed the add-on is using for TechSNAP has been discontinued by JB.  As such, new episodes are currently not available via the TechSNAP entry in the add-on (though they can still be viewed under the "Most Recent" section).

The new video feed is at http://feedpress.me/techsnapvid.

While you're in there, both the show icon and show description are from 1st-gen TechSNAP.  It would be nice to update them both for 3rd-gen TechSNAP.

Thanks!

**Comment by RobLoach** [comment]
Feel free to update it over in https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting/blob/frodo/jb_shows.py .

Thanks a lot!

**Comment by blkeller** [comment]
Okie dokie: #90

**Comment by RobLoach** [comment]
Nicely done! :+1:

**Comment by blkeller** [comment]
Thanks.  Any chance of seeing these changes in a new release to the Kodi add-on catalog?  The most recent version available there is 3.4.0, which is missing all changes made after May of 2017.

**Comment by RobLoach** [comment]
@blkeller Good call! I'll make an issue so that we can go through another round of updates and get the new version out.
